services:
  web:
    image: php:8.2-apache
    volumes:
      - ./app:/var/www/html/
    ports:
      - '80:80'
    environment:
      APPLICATION_ENV: development
      APACHE_LOG_DIR: /var/log/apache2
      APACHE_DOCUMENT_ROOT: /var/www/html
