services:
  backend:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    environment:
      - PORT=80
    deploy:
      replicas: 5
    networks:
      - loadbalancing

  nginx:
    build:
      context: ./docker/nginx/
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - loadbalancing
    depends_on:
      - backend

networks:
  loadbalancing:
