services:
  backend:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    environment:
      - PORT=80
    deploy:
      replicas: 5
    networks:
      - loadbalancing
  nginx:
    build:
      context: ./docker/nginx/
      dockerfile: Dockerfile
    container_name: load_balancer
    ports:
      - "81:80"
    networks:
      - loadbalancing
    depends_on:
      - backend
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8080:8080"
    networks:
      - loadbalancing
    volumes:
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    privileged: true
    devices:
      - "/dev/kmsg"
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - loadbalancing
    depends_on:
      - cadvisor
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - "./grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "3000:3000"
    networks:
      - loadbalancing
    depends_on:
      - prometheus

networks:
  loadbalancing:
