services:
  backend:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    environment:
      - PORT=80
    deploy:
      replicas: 5
    networks:
      - loadbalancing
  nginx:
    build:
      context: ./docker/nginx/
      dockerfile: Dockerfile
    container_name: load_balancer
    ports:
      - "81:80"
    networks:
      - loadbalancing
    depends_on:
      - backend
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    privileged: true
    devices:
      - "/dev/kmsg"

networks:
  loadbalancing:
